Add files via upload
Looked into the algorithm and tried to convert into code.Was getting following errors:
./Solution.java:33: error: unexpected type
    a.get(i)=a.get(j);
         ^
  required: variable
  found:    value
./Solution.java:34: error: unexpected type
    a.get(j)=temp;
         ^
  required: variable
  found:    value
2 errors